In [1]:
import numpy as np

###  Creating Arrays

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([(1, 2), (3, 4)], dtype=float)
print(b)

[[1. 2.]
 [3. 4.]]


In [4]:
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20]]], dtype=np.float64)
print(c)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 1.  2.  3.  4.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]]]


In [5]:
type(c), c.dtype, c.ndim, c.shape, c.size # rows*cols

(numpy.ndarray, dtype('float64'), 3, (3, 2, 4), 24)

### Initial Placeholders 

In [6]:
d = np.zeros(shape=(3, 4), dtype=np.int64)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
e = np.ones(shape=(2, 3, 4), dtype=np.int16)
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
f = np.arange(start=10, stop=25, step=5)
print(f)

[10 15 20]


In [9]:
g = np.linspace(start=0, stop=2, num=5, endpoint=True)
print(g)

g1 = np.linspace(start=0, stop=2, num=5, endpoint=False)
print(g1)

[0.  0.5 1.  1.5 2. ]
[0.  0.4 0.8 1.2 1.6]


In [10]:
h = np.full(shape=(2, 3), fill_value=5.7, dtype=float)
print(h)

[[5.7 5.7 5.7]
 [5.7 5.7 5.7]]


In [11]:
i = np.eye(N=10, # rows
           M=5,  # cols
           k=-2, # diagonal (+ve upper diag, -ve lower diag)
           dtype=np.int64)
print(i)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
j = np.random.random(size=(3, 3)) # values between 0 and 1
print(j)

[[0.48687535 0.66537065 0.75547587]
 [0.71575627 0.46654014 0.07481688]
 [0.05375964 0.44009046 0.27175705]]


In [13]:
k = np.empty(shape=(3, 3), dtype=np.int64) # garbage
print(k)

[[4602442386419939582 4604168345600315239 4604979941202324763]
 [4604622178894040290 4602076059897848718 4590055544933654224]
 [4587908401751215120 4601599584764273034 4598567159721511354]]


### Input/Output

#### arrays

In [14]:
np.save("my_array.npy", a)
loaded_array = np.load("my_array.npy")
print(loaded_array)

[1 2 3]


In [15]:
np.savez("my_arrays.npz", my_array1=a, my_array2=b, my_array3=c)
loaded_data = np.load("my_arrays.npz")
loaded_array1 = loaded_data["my_array1"]
loaded_array2 = loaded_data["my_array2"]
loaded_array3 = loaded_data["my_array3"]
# print(loaded_array1) # a
# print(loaded_array2) # b
# print(loaded_array3) # c

#### text

In [16]:
np.savetxt('my_array.txt', a, delimiter=',')
np.savetxt('my_array.csv', a, delimiter=',') # comma seperated values
np.savetxt('my_array.out', a, delimiter=',') # assembler output

In [17]:
# create and add data into data.txt
with open('data.txt', 'w+') as f:
    f.write('''Value1  Value2  Value3
0.2536  0.1008  0.3857
0.4839  0.4536  0.3561
0.1292  0.6875  0.5929
0.1781  0.3049  0.8928
0.6253  0.3486  0.8791''')

In [18]:
# create and add data into data2.txt (contains missing values)
with open('data2.txt', 'w+') as f:
    f.write('''Value1  Value2  Value3
0.4839  0.4536  0.3561
0.1292  0.6875  MISSING
0.1781  0.3049  0.8928
MISSING 0.5801  0.2038
0.5993  0.4357  0.7410''')

In [19]:
arr1 = np.genfromtxt('data.txt')
arr2 = np.genfromtxt('data2.txt', skip_header=1, filling_values=-99)

In [20]:
print(arr1)
print(arr2)

[[   nan    nan    nan]
 [0.2536 0.1008 0.3857]
 [0.4839 0.4536 0.3561]
 [0.1292 0.6875 0.5929]
 [0.1781 0.3049 0.8928]
 [0.6253 0.3486 0.8791]]
[[  0.4839   0.4536   0.3561]
 [  0.1292   0.6875 -99.    ]
 [  0.1781   0.3049   0.8928]
 [-99.       0.5801   0.2038]
 [  0.5993   0.4357   0.741 ]]


In [21]:
arr3 = np.loadtxt('data.txt', dtype=str) 
arr4 = np.loadtxt('data.txt', dtype=str, delimiter='\n') # \n delimiter => each row a str

In [22]:
print(arr3)
print(arr4)

[['Value1' 'Value2' 'Value3']
 ['0.2536' '0.1008' '0.3857']
 ['0.4839' '0.4536' '0.3561']
 ['0.1292' '0.6875' '0.5929']
 ['0.1781' '0.3049' '0.8928']
 ['0.6253' '0.3486' '0.8791']]
['Value1  Value2  Value3' '0.2536  0.1008  0.3857'
 '0.4839  0.4536  0.3561' '0.1292  0.6875  0.5929'
 '0.1781  0.3049  0.8928' '0.6253  0.3486  0.8791']


In [23]:
x, y, z = np.loadtxt('data.txt', skiprows=1, unpack=True)
print(x,y,z, sep='\n') # each col in file is stored as array

[0.2536 0.4839 0.1292 0.1781 0.6253]
[0.1008 0.4536 0.6875 0.3049 0.3486]
[0.3857 0.3561 0.5929 0.8928 0.8791]


In [24]:
# x, y, z = np.loadtxt('data2.txt', skiprows=1, unpack=True)
# ValueError: could not convert string to float: 'MISSING'

### Inspecting array

In [25]:
print(a)

[1 2 3]


In [26]:
print(a.ndim, # 1
      len(a), # 3
      a.shape, # (3,)
      a.size, # 3
      a.itemsize, # 4
      a.nbytes, # 3*4 = 12
      a.dtype, # int32
      a.dtype.name, # int32
      a[0].dtype, # int32
      sep='  ')

1  3  (3,)  3  4  12  int32  int32  int32


In [27]:
print(b)

[[1. 2.]
 [3. 4.]]


In [28]:
print(b.ndim, # 2
      len(b), # 2 rows
      b.shape, # (2,2)
      b.size, # 4
      b.itemsize, # 8
      b.nbytes, # 4*8 = 32
      b.dtype, # float64
      b.dtype.name, # float64
      b[0][0].dtype, # float64
      sep='\t')

2	2	(2, 2)	4	8	32	float64	float64	float64


In [29]:
print(c)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 1.  2.  3.  4.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]]]


In [30]:
print(c.ndim, # 3
      len(c), # 3 rows
      c.shape, # (3,2,4)
      c.size, # 24
      c.itemsize, # 8
      c.nbytes, # 24*8 = 192
      c.dtype, # float64
      type(c), # numpy.ndarray
      type(c[0]), # numpy.ndarray
      type(c[0][0]), # numpy.ndarray
      sep='  ')

3  3  (3, 2, 4)  24  8  192  float64  <class 'numpy.ndarray'>  <class 'numpy.ndarray'>  <class 'numpy.ndarray'>


In [31]:
s = np.array([['a','an','the'],['python','is','easy']])
print(s.ndim, # 2
      len(s), # 2 rows
      s.shape, # (2,3)
      s.size, # 6 (largest string length)
      s.itemsize, # 24
      s.nbytes, # 24*6 = 144
      s.dtype, # <U6
      type(s), # numpy.ndarray
      type(s[0]), # numpy.ndarray
      type(s[0][0]), # numpy.str_
      sep='  ')

2  2  (2, 3)  6  24  144  <U6  <class 'numpy.ndarray'>  <class 'numpy.ndarray'>  <class 'numpy.str_'>


### Data Types

***numpy data types***

- np.int64 # Signed 64-bit integer types
- np.float32 # 8 bits exponent, 23 bits mantissa
- np.double # 11 bits exponent, 52 bits mantissa
- complex # Complex numbers represented by 128 floats
- bool # Boolean type storing TRUE and FALSE values
- object # Python object type
- np.string_ # Fixed-length string type
- np.unicode_ # Fixed-length unicode 

***referring datatypes with 1 character:***

- i # integer
- b # boolean
- u # unsigned integer
- f # float
- c # complex float
- m # timedelta
- M # datetime
- O # object
- S # string
- U # unicode string
- V # fixed chunk of memory for other type ( void )

In [32]:
a = np.power(100, 8, dtype=np.int64)
a2 = np.power(100, 8, dtype=np.int32) # garbage as size exceeds
b = np.array([1, 2, 3], dtype='f')
c = np.array([1, 2, 3], dtype=np.float32)
d = np.array([1, 2, 3], dtype=np.str_)

In [33]:
print(a,a2,b,c,d)
print(a.dtype,b.dtype,c.dtype,d.dtype)

10000000000000000 1874919424 [1. 2. 3.] [1. 2. 3.] ['1' '2' '3']
int64 float32 float32 <U1


#### Casting

In [34]:
b_str = b.astype(np.str_)
print(b, b_str, b.dtype, b_str.dtype)

[1. 2. 3.] ['1.0' '2.0' '3.0'] float32 <U32


### Math Operations

In [35]:
# shape should match or one array should be a scalar
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
s = 5

In [36]:
# a and b shape matches
print(np.add(a, b), # [2 4 6]
      np.subtract(a, b), # [0 0 0]
      np.diff(a), # [1 1] consecutive elementdifference
      np.multiply(a, b), # [1 4 9]
      np.divide(b, a), # [1. 1. 1.]
      np.exp(a), # e^a_elements [ 2.71828183  7.3890561  20.08553692]
      np.sqrt(b), # [1.         1.41421356 1.73205081]
      np.dot(a,b), # matrix dot product: 14
      
      # Comparison Operations
      a == b, # array operation (elementwise) [ True  True  True]
      a < 2, # [ True False False]
      np.array_equal(a, b), # arrray content comparision True
      a is b, # array object with content comparision False
     sep=' ')

[2 4 6] [0 0 0] [1 1] [1 4 9] [1. 1. 1.] [ 2.71828183  7.3890561  20.08553692] [1.         1.41421356 1.73205081] 14 [ True  True  True] [ True False False] True False


In [37]:
# s is sclare and a is array
print(np.add(a, s), # [6 7 8]
      np.subtract(a, s), # [-4 -3 -2]
      np.multiply(a, s), # [ 5 10 15]
      np.divide(b, s), # [0.2 0.4 0.6]
      np.exp(s), # e^5
      np.sqrt(s), # sqrt(5)=2.23606797749979
      np.dot(a,s), # element wise multiplycation: [ 5 10 15]
    
      # Comparison Operations
      a == s, # elementwise comparision [False False False]
      a < s, # [ True  True  True]
      np.array_equal(a, s), # False
      a is s, # False
      sep=' ')

[6 7 8] [-4 -3 -2] [ 5 10 15] [0.2 0.4 0.6] 148.4131591025766 2.23606797749979 [ 5 10 15] [False False False] [ True  True  True] False False


In [38]:
# columns should be equal. compatible in all dimensions
x = np.ones((2,3))
y = np.full((5,1,3),4)
z = x + y
print(z.shape)
# print(x,y,z)

(5, 2, 3)


In [39]:
b = np.array([(1, 2), (3, 4)], dtype=float)
# x + b # ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [40]:
# division by 0
print(np.divide(a, 0)) # [inf, inf, inf]
print(np.divide(-a, 0)) # [-inf, -inf, -inf]

[inf inf inf]
[-inf -inf -inf]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_33572\2220532672.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(a, 0)) # [inf, inf, inf]
C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_33572\2220532672.py:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(-a, 0)) # [-inf, -inf, -inf]


In [41]:
print(np.sin(a), 
      np.cos(a), 
      np.tan(a), 
      np.log(a), sep='\n')

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[0.         0.69314718 1.09861229]


In [42]:
a = np.array([1.6, 2.2, 3.09])
print(np.floor(a), 
      np.ceil(a), sep='\n')

[1. 2. 3.]
[2. 3. 4.]


### Aggregate Functions

In [43]:
a = np.array([1, 2, 3])
print(a.sum(), 
      a.min(), 
      a.max(), 
      a.cumsum(), 
      a.mean(), 
      np.median(a), 
      np.corrcoef(a), 
      sep=' ')

6 1 3 [1 3 6] 2.0 2.0 1.0


In [44]:
a = np.array([[1, 2, 2],[4, 5, 6]])
print(a.sum(), 
      a.min(), 
      a.max(), 
      a.cumsum(), 
      a.mean(), 
      np.median(a), 
      sep=' ')
print(np.corrcoef(a))

20 1 6 [ 1  3  5  9 14 20] 3.3333333333333335 3.0
[[1.        0.8660254]
 [0.8660254 1.       ]]


In [45]:
a = np.array([[10, 5, 2],[4, 5, 6]])
print(np.corrcoef(a))

[[ 1.         -0.98974332]
 [-0.98974332  1.        ]]


### Statistical functions

In [46]:
a = np.array([10, 5, 2, 4])
b = a.reshape(2,-1)

print(np.mean(a),
      np.std(a),
      np.var(a),
      np.median(a),
      np.percentile(a, 50),
      np.percentile(a, 75),
      np.percentile(a, 100),
      np.trace(b)) # 10+4

5.25 2.947456530637899 8.6875 4.5 4.5 6.25 10.0 14


### copying

In [47]:
# Copying
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = a
print(a is b, a is c, b is c)

False True False


In [48]:
d = a[:] # shallow copy
e = np.copy(a) # deep copy
f = a.copy() # deep copy
d[0] = 10
e[1] = 20
f[2] = 30
print(a)
print(d)
print(e)
print(f)

[10  2  3]
[10  2  3]
[ 1 20  3]
[ 1  2 30]


### views

Ex: Image processing
1. Capture the image using the camera and convert it into a NumPy array.
2. Create a view of the NumPy array to work with a specific region of the image (e.g., a rectangular portion).
3. Apply the sepia filter to the view of the image, which modifies the pixel values directly in the view without copying the entire image data.
4. Display the modified portion of the image in real-time.

In [49]:
# use of view

original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array[1:4]
v2 = original_array.view()

print("Original Array:", original_array)
print("View Array:", view_array)
print("View2:", v2)

# Modify the view array
view_array[:] = 100
print("Modified View Array:", view_array)

v2[1:2] = 200 
print("Modified V2:", v2) # changes from above view are also there

print("Modified Original Array:", original_array) # changes from all views existEx: Image processing

Original Array: [1 2 3 4 5]
View Array: [2 3 4]
View2: [1 2 3 4 5]
Modified View Array: [100 100 100]
Modified V2: [  1 200 100 100   5]
Modified Original Array: [  1 200 100 100   5]


### Transpose

In [50]:
a = np.array([[1,2,3],[4,5,6]])
# a = np.array([[1,2,3,4,5,6]])
# a = np.array([1,2,3,4,5,6])

b = np.transpose(a)
c = a.T
print(a.shape, b.shape, c.shape)

(2, 3) (3, 2) (3, 2)


### Indexing, Subsetting, Slicing

In [51]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0], 
      a[-1],
      a[a > 4], # boolean indexing
      a[-1][-1], # subsetting
      a[-1, -1],
      sep='\n')

[1 2 3]
[4 5 6]
[5 6]
6
6


In [52]:
print(a[1:], # slicing
      a[-1, :], 
      a[:, 2], 
      a[:2, 1], 
      a[:1,1:],
      a[1, ...], # a[1,:]
      a[[0, 0, -1, 1], [0, 1, -1, 2]], 
      a[1,-2:-4:-1],
     sep='\n')

[[4 5 6]]
[4 5 6]
[3 6]
[2 5]
[[2 3]]
[4 5 6]
[1 2 6 6]
[5 4]


In [53]:
# fancy indexing
print(a[[1,0,1,0]], # select rows
      a[[1,0,1,0]][:], # select rows and all columns 
      a[[1,0,1,0]][:,[0,1,2,1]], # select rows and specified columns
      sep="\n")

[[4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]
[[4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]
[[4 5 6 5]
 [1 2 3 2]
 [4 5 6 5]
 [1 2 3 2]]


### array manipulation

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9],[10,11,12]])
print(a.shape)
print(a)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
# Reshape array 'a' into a 3x3 matrix
reshaped_a = a.reshape((3, 4))
print('reshaped_a',reshaped_a.shape)
print(reshaped_a)

reshaped_a (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
# -1 evaluates the last value in reshape according to the total number of elements in the array
reshaped_a = a.reshape((1,-1)) 
print('reshaped_a',reshaped_a.shape)
print(reshaped_a)

reshaped_a (1, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [57]:
reshaped_a = a.reshape((2,-1)) # 
print('reshaped_a',reshaped_a.shape)
print(reshaped_a)

reshaped_a (2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [58]:
reshaped_a = a.reshape((1,3,-1)) # 
print('reshaped_a',reshaped_a.shape)
print(reshaped_a)

reshaped_a (1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [59]:
# Resize array 'a' to a new shape (2x4), potentially repeating elements
resized_a = np.resize(a, (2, 4)) # data loss possible
print('resized_a',resized_a.shape)
print(resized_a)

resized_a (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [60]:
# Flatten array 'a' (convert multi-dimensional array to a 1D array)
raveled_a = np.ravel(a)
print('raveled_a',raveled_a)

# Flatten array 'a' using the default row-major order (equivalent to np.ravel(a))
flattened_a = a.flatten()
print('flattened_a',flattened_a)

# Append value 7 to the end of array 'a'
appended_a = np.append(a, 7)
print('appended_a',appended_a)

# Insert value 3 into array 'a' at index 2
inserted_a = np.insert(a, 2, 300)
print('inserted_a',inserted_a)

# Delete element at index 2from array 'a'
deleted_a = np.delete(a, 11)
print('deleted_a',deleted_a)
# print(a)

raveled_a [ 1  2  3  4  5  6  7  8  9 10 11 12]
flattened_a [ 1  2  3  4  5  6  7  8  9 10 11 12]
appended_a [ 1  2  3  4  5  6  7  8  9 10 11 12  7]
inserted_a [  1   2 300   3   4   5   6   7   8   9  10  11  12]
deleted_a [ 1  2  3  4  5  6  7  8  9 10 11]


### Sorting Arrays

- **axis = 0 => vertical axis**
- **axis = 1 => horizontal axis**

In [61]:
# demonstrating axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
arr.sum(axis=0), arr.sum(axis=1), arr.sum(axis=None) # default

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([12, 15, 18]), array([ 6, 15, 24]), 45)

In [62]:
a = np.array([[30,10,1], [6,50,3]])
print(a)

[[30 10  1]
 [ 6 50  3]]


In [63]:
a.sort(axis=1) # horizontal axis
print(a)

[[ 1 10 30]
 [ 3  6 50]]


In [64]:
a.sort(axis=0) # vertical axis
print(a) # original is affected

[[ 1  6 30]
 [ 3 10 50]]


In [65]:
a = np.array([[30,10,1], [6,50,3]])
a.sort(axis=-1) # last axis
print(a)

[[ 1 10 30]
 [ 3  6 50]]


In [66]:
a = np.array([[30,10,1], [6,50,3]])
b = np.sort(a) # original is not affected
print(b)
print(a)

[[ 1 10 30]
 [ 3  6 50]]
[[30 10  1]
 [ 6 50  3]]


### Combining arrays

In [67]:
a = np.array([(1, 2), (3, 4)], dtype=float)
b = np.array([(5, 6), (7, 8)], dtype=float)
print(a)
print(b)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [68]:
np.vstack((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [69]:
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [70]:
np.concatenate((a, b), axis=0) # vstack

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [71]:
np.concatenate((a, b), axis=1) # hstack

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

### Splitting arrays

In [72]:
a = np.array([(1, 2), (3, 4), (5,6)], dtype=float)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [73]:
a1, a2, a3 = np.vsplit(a, 3) # each row is splitted
print(a1)
print(a2)
print(a3)

[[1. 2.]]
[[3. 4.]]
[[5. 6.]]


In [74]:
a1, a2 = np.hsplit(a, 2) # each column is splitted
print(a1)
print(a2)

[[1.]
 [3.]
 [5.]]
[[2.]
 [4.]
 [6.]]


### Data analysis functions

In [75]:
a = np.array([(1, 2), (8, 4), (8,6)], dtype=int)
f = a.ravel()
t = np.array([np.inf, 5, np.nan])
print(a)
print(f)
print(t)

[[1 2]
 [8 4]
 [8 6]]
[1 2 8 4 8 6]
[inf  5. nan]


In [76]:
# indicies
print(np.argsort(f), 
      np.argmax(a),
      np.argmin(a),
      np.where(a > 5),
     )

[0 1 3 5 2 4] 2 0 (array([1, 2, 2], dtype=int64), array([0, 0, 1], dtype=int64))


In [77]:
# 
print(
      np.bincount(f), # count of 0 to 8 values
      np.histogram(a, bins=4), # count of values across 4 bins
      np.isinf(t),
      np.isnan(t),
      np.random.choice(f, size=3),
      sep='\n')

[0 1 1 0 1 0 1 0 2]
(array([2, 1, 1, 2], dtype=int64), array([1.  , 2.75, 4.5 , 6.25, 8.  ]))
[ True False False]
[False False  True]
[8 6 1]


In [78]:
unq_ele, counts = np.unique(a, return_counts=True)
print(unq_ele, counts)

[1 2 4 6 8] [1 1 1 1 2]


### masked arrays

In [79]:
# Create a regular NumPy array with some missing values (e.g., represented by -999)
data = np.array([10, 20, -999, 30, -999, 40, 50, -999])

# Create a masked array by specifying the condition for missing values
masked_data = np.ma.masked_where(data == -999, data)

print("Original Data:", data)
print("Masked Array:", masked_data)

Original Data: [  10   20 -999   30 -999   40   50 -999]
Masked Array: [10 20 -- 30 -- 40 50 --]


In [80]:
# Perform calculations on the masked array (missing values will be ignored)
mean = np.mean(masked_data)
sum = np.sum(masked_data)

print("Mean:", mean)
print("Sum:", sum)

Mean: 30.0
Sum: 150
